apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: zvakiemjt-python 
  janus-idp.io/tekton: zvakiemjt-python
  backstage.io/kubernetes-id: zvakiemjt-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zvakiemjt-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  